### PR TITLE
faf-client: build from source

### PR DESCRIPTION
**Pull request by chayleaf**
Ideally we'd use Nixpkgs's `openjdk` instead of `openjdk17-bootstrap`... but I'm really not sure how to get it to work.

Currently, there seems to be a CI bug in that the lockfiles can't be copied to build directory via `cp ${./gradle.lockfile} gradle.lockfile`

Commit overview:

- `bin.nix` - renamed from old default.nix
  - `update.sh` - old update script is changed a bit. One bug is fixed (base64 hashes containing `/` didn't work)
- `default.nix` - the faf client itself, built from source
  - `gradle-{stable,unstable}.lockfile` - gradle lockfiles of faf client (to ensure reproducibility)
  - `start.sh` - a start script. It sets the necessary env vars and java arguments. 
  - `disable-update-check.patch` - a patch to disable update check (the client doesn't start if updates are detected). This breaks tests.
  - `ice-adapter.nix` - a dependency of faf client, normally it's downloaded from Github but I decided to build it from source instead.
    - `gradle-ice.lockfile` - gradle lockfile
  - `uid.nix` - another dependency of faf client. This one is a native binary.
  - `update-src.sh` - update script. It checks if the pins got updated, and if so, generates a new lockfile and updates the dependencies' hash.
    - `info.json` - used by the update script to cache the current version.
- `init.gradle` - a helper gradle script that replaces remote repositories with a local one.
- The way Gradle builds work is:
  - Pure derivations without a known output hash can't access the internet. Yet we need internet access to download Gradle dependencies.
  - So a `${pname}-deps` derivation is built, using a version controlled `gradle.lockfile` to ensure the same dependencies are pulled every time. The derivation simply downloads the dependencies. Thanks to `gradle.lockfile`, the output hash should match every time.
    - Except locking doesn't work for `SNAPSHOT` dependencies, so those are changed to use `latest.integration` instead (which is essentially the same, but allows locking)
  - A perl script is used to convert the download dependency cache into a maven repository.
  - The `deps` derivation outputs the maven repo, as well as the lockfile.
  - If the lockfile needs to be updated, `deps.updateLockfile` is used to build a version of `deps` with fresh dependencies, generating a new lockfile rather than using the one in-tree. It's used by the update script.

TODO: custom patches 
- [ ] maybe hardcode natives path so the files don't have to be in both `lib/` and `natives/` and so we don't have to `cd`
- [ ] respect XDG (`src/main/java/com/faforever/client/os/OsPosix.java`)
- [x] disable update check (`src/main/java/com/faforever/client/update/Version.java` line 43)
- [ ] build [map generator](https://github.com/FAForever/Neroxis-Map-Generator) from source rather than download it (`src/main/java/com/faforever/client/map/generator/MapGeneratorService.java` line 199)

Patch 2 is [here](https://gist.github.com/chayleaf/4c1fb03ee231b071d002b8010faa92ae), but that requires changes to `LOG_DIR` env var and `faf-client-setup`. Frankly, I'd rather it be upstreamed, otherwise it can be a major source of bugs.

Patches are actually rather easy to apply with this even for end users, as the longest build step is resolving dependencies, and dependencies are cached between builds

### CODE REVIEW

**Comment by chayleaf** [comment]
@fufexan I give up, what could cause the CI error?

**Comment by fufexan** [comment]
@chayleaf from the log it looks like these might be the offending lines https://github.com/fufexan/nix-gaming/pull/57/files#diff-c8d9d9f4769bb0b94b637b4a2adddc9dfb87e0406da822336b2b8185e81da354R32-R34.
Does the file exist at that location? Maybe you need to `cd source` first?

**Comment by chayleaf** [comment]
it absolutely does, it builds fine on my machine(tm)

**Comment by fufexan** [comment]
Also fails on my machine.

**Comment by chayleaf** [comment]
What command are you using? I'm just doing `nix build .#faf-client`

**Comment by chayleaf** [comment]
the issue was twofold - I forgot to check whether `deps` itself can build without using `deps.updateLockfile` (the hash is supposed to be the same so Nix considered it to have the same result, and I did too), and also turns out when Gradle generates the lockfile, it also caches metadata of versions that it won't actually use when using the lockfile (i.e. old versions of packages), so I had to make the `.updateLockfile` derivation generate the lockfile, nuke the cache and rebuild it with the new lockfile to ensure the hash matches

**Comment by chayleaf** [comment]
The solution was quite simple - sorting the directory entries during installation, since more than one version of a plugin may be stored in the cache at a time, but only one may be stored in a maven repo.

**Comment by chayleaf** [comment]
@fufexan this is ready

**Comment by fufexan** [comment]
Sorry for the delay, had some exams to study for.

Overall LGTM, although a bit huge.

**Comment by chayleaf** [comment]
oops, faf-client-bin is now duplicated in the readme

**Comment by fufexan** [comment]
I'll fix it, don't worry.

**Pull request merged**
