### PR TITLE
bump pkgs.osu-stable sh256 sum

### PR DESCRIPTION
**Pull request by jamesbt365**
It happened again.
image

### CODE REVIEW

**Comment by fufexan** [comment]
Thanks!

**Comment by boppyt** [comment]
Apologies for commenting in a closed PR,

@fufexan Would it be possible to automate this bump by regularly checking the `Last-Modified | ETag` header of ppy.sh mirror?

**Comment by fufexan** [comment]
@boppyt possibly yes, we could make a cronjob that runs daily. Should be done alongside the npins stuff.

I won't have much time to work on it until next month though, so if anyone wants to do it I'll be happy to review.

**Comment by boppyt** [comment]
> @boppyt possibly yes, we could make a cronjob that runs daily. Should be done alongside the npins stuff.
> 
> I won't have much time to work on it until next month though, so if anyone wants to do it I'll be happy to review.

Seems like we could use `update-nix-fetchgit` to only bump the `fetchUrl` part of the `osu-stable/default.nix` file.
Although it seems to throw error when used with the osu-stable's fetchUrl block since it doesn't respect the `name` attribute. Once that's cleared up, I'll open a PR.

**Pull request merged**
