### PR TITLE
add: proton-osu-bin and umu osu

### PR DESCRIPTION
**Pull request by ProspectPyxis**
This PR does two things:

- It creates a new `proton-osu-bin` package, packaged from the build artifacts of https://github.com/whrvt/umubuilder. The code is directly copied from `proton-ge-bin` in base `nixpkgs`.
- It adds `umu` capabilities to `osu-stable`, similar to `star-citizen`. This is set to use the aforementioned `proton-osu` by default.

Related to #207 - this doesn't directly fix `wine-osu`, but adds a new method to run `osu-stable` with patches that provide the same benefit.

**The issue below has been solved!** This PR is fully functional - I will leave the logs here for archival purposes, though.

---

Unfortunately, I'm currently unable to get the `useUmu` version working on my machine - the install process works fine, but the game crashes immediately after the icon splash, complaining about driver files. Here are the logs (removing extraneous logs from `gamemoderun`):

<details>

<summary>Crash Log</summary>

```
ProtonFixes[604843] INFO: Running protonfixes
ProtonFixes[604843] INFO: Running checks
ProtonFixes[604843] INFO: All checks successful
ProtonFixes[604843] WARN: Game title not found in CSV
ProtonFixes[604843] INFO: Non-steam game UNKNOWN (osu-wine-umu)
ProtonFixes[604843] INFO: No store specified, using UMU database
ProtonFixes[604843] INFO: Using global defaults for UNKNOWN (osu-wine-umu)
ProtonFixes[604843] INFO: Non-steam game UNKNOWN (osu-wine-umu)
ProtonFixes[604843] INFO: No store specified, using UMU database
ProtonFixes[604843] INFO: No global protonfix found for UNKNOWN (osu-wine-umu)
Proton: /home/user/.osu/drive_c/osu/osu!.exe
Proton: Executable a unix path, launching with /unix option.
fsync: up and running.
wineserver: failed to change priority to SCHED_FIFO/1
libGL error: MESA-LOADER: failed to open iris: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/iris_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/iris_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/swrast_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  521
  Current serial number in output stream:  520
```

</details>

This happens regardless of the proton version used - I've set it to `proton-ge-bin` as well for the same result.

I'm unsure why this error occurs, and am submitting this PR now in hopes of getting more eyes on the problem.

### CODE REVIEW

**Comment by ProspectPyxis** [comment]
Apparently umu being broken is an upstream issue: Open-Wine-Components/umu-launcher#246

Also, what program is used to format? I'd like to fix the broken formatting.

**Comment by ProspectPyxis** [comment]
Upstream bug has been fixed and tests are now passing.

Whenever umu is updated in this flake, this should be good to merge.

**Comment by ProspectPyxis** [comment]
Apologies for the bump, but is anything else needed for this to be merged? I've been using this branch personally with umu enabled with no problems.

**Comment by fufexan** [comment]
Oh, I forgot about this. Should've pinged me sooner.

**Review by fufexan — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
