### PR TITLE
Update proton-osu-bin + add proton-osu to npins

### PR DESCRIPTION
**Pull request by ProspectPyxis**
Bumps proton-osu-bin to the latest version. Forgot to update this with the last PR, whoops.

Also taking this opportunity to fix a little typo in the updated README file.

### CODE REVIEW

**Review by fufexan — COMMENTED** [review]
`proton-osu-bin` can be added to `npins` and be auto-updated.

**Comment by ProspectPyxis** [comment]
`proton-osu` has been added to npins.

It's a bit awkward, though, since npins can't parse the way the proton-osu repo tags its releases without removing the entire `proton-osu-9-` prefix. This will have to be manually updated if there's ever a proton-osu-10-x release.

**Review by fufexan — APPROVED** [review]
Looks good for now. We could also drop it from npins and handle hashing in the script directly, if you feel this is more future-proof.

**Comment by ProspectPyxis** [comment]
It should be fine for the time being - I don't foresee a 10.x release any time soon, and we should probably do a manual update in that case anyways just so we're aware of breaking changes. I'll get back to this if it becomes necessary.

Feel free to merge.

**Pull request merged**
