### PR TITLE
star-citizen 1.6.10 -> 2.0.5

### PR DESCRIPTION
**Pull request by LovingMelody**
* Bump star-citizen to 2.0.3
* Bump winetricks to git versions
* Add options `enableGameScope` `gameScopeArgs`

### CODE REVIEW

**Comment by LovingMelody** [comment]
Placing this as draft, submitting a PR to nixpkgs for proton-ge-9-12 which would change things for this package as well.

**Comment by LovingMelody** [comment]
Considering bumping this to 2.0 launcher, proton-ge-12 has the powershell fixes. latest git for winetricks has it as well.

@fufexan do you have any opinions on adding winetricks-git to this repo?

**Comment by fufexan** [comment]
No objections, feel free.

**Comment by LovingMelody** [comment]
proton-ge-bin update is now in nixpkgs-unstable
this PR is not ready to be merged until #201 is in

**Comment by LovingMelody** [comment]
Confirmed game is running as expected.

**Review by fufexan — APPROVED** [review]
LGTM. Sorry for the delay!

**Comment by fufexan** [comment]
Oops, looks like npins is conflicting.

**Comment by LovingMelody** [comment]
Launcher has been bumped to 2.0.5 and wine has been updated from wine-ge to latest wine stable.

**Review by fufexan — APPROVED** [review]
LGTM

**Pull request merged**
