### PR TITLE
Update star-citizen: 2.0.5 -> 2.1.0

### LINKED ISSUE #206: Broken launcher from .desktop file
After the update to RSI launcher 2.0, I'm getting this error when clicking on the 'Applications' icon for star citizen.

image

The desktop file is
```ini
# /home/damccull/.local/share/applications/wine/Programs/Roberts Space Industries/RSI\ Launcher.desktop

[Desktop Entry]
Name=RSI Launcher
Exec=env WINEPREFIX="/home/damccull/Games/star-citizen" wine C:\\\\ProgramData\\\\Microsoft\\\\Windows\\\\Start\\ Menu\\\\Programs\\\\Roberts\\ Space\\ Industries\\\\RSI\\ Launcher.lnk
Type=Application
StartupNotify=true
Comment=RSI Launcher
Path=/home/damccull/Games/star-citizen/dosdevices/c:/Program Files/Roberts Space Industries/RSI Launcher
Icon=341A_RSI Launcher.0
StartupWMClass=rsi launcher.exe

```

However, when I run it from the terminal with the command 'star-citizen', it launches just fine. How do I solve this?

### PR DESCRIPTION
**Pull request by LovingMelody**
* Bump launcher version to 2.1.0

* Add work around for java script error 

fixes #206

### CODE REVIEW

**Comment by LovingMelody** [comment]
@damccull can you test if this fixes your issue?

**Comment by damccull** [comment]
> @damccull can you test if this fixes your issue?

Yes, I would love to. How do I target this PR to install this version as a test? I'm still learning nixos, and using a flake. Do I just set the input to github and point at this PR specifically?

**Comment by fufexan** [comment]
@damccull change the nix-gaming input url to `github:LovingMelody/nix-gaming/update-star-citizen`, and rebuild.

**Comment by LovingMelody** [comment]
Force push changes:

* Updated dll overrides to prevent wine from creating desktop icons
* Set `WINEDEBUG=-all` to reduce wine debug messages

**Comment by LovingMelody** [comment]
Updated packaged to use a cleaner work around. I have tested with `systemd-run --user -d -- nix run .\#star-citizen` to ensure the issue isnt present still.

**Comment by damccull** [comment]
I have changed to the repo you mentioned, and even rebooted. Still, typing `star-citizen` in the terminal will launch it fine but I get the same issue when clicking the shortcut in the apps menu.

> @damccull change the nix-gaming input url to `github:LovingMelody/nix-gaming/update-star-citizen`, and rebuild.

**Comment by damccull** [comment]
> What desktop environment are you using?

Good question that I hadn't considered. It is the default that NixOS seems to use. Gnome on Wayland I believe.

Thanks for being patient with me. I'm familiar with Linux in a server context but I'm still adjusting to 20+ years of Windows use for a desktop environment.

**Comment by LovingMelody** [comment]
Hmm, it should be using systemd-run, I will have to look further into this. The umu variant shouldn't have this problem if you wish to try it.

**Comment by LovingMelody** [comment]
@damccull what branch of nixpkgs are you on (ideally the commit as well)?

**Comment by damccull** [comment]
I am currently using nixos-unstable, and my flake.lock says.... (drumroll)
```json
    "nixpkgs": {
      "locked": {
        "lastModified": 1718714799,
        "narHash": "sha256-FUZpz9rg3gL8NVPKbqU8ei1VkPLsTIfAJ2fdAf5qjak=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "c00d587b1a1afbf200b1d8f0b0e4ba9deb1c7f0e",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
```
This is what you wondered? I update every couple weeks but this is what I last tried it on and am currently running.

**Comment by LovingMelody** [comment]
I cannot recreate your issue with this pr, I can on master.

**Comment by damccull** [comment]
Ok, I'll do a complete SC wipe and reinstall, including deleting the Wine folder, removing it from the config, running nix garbage collector. I'll also do an update of NixOS. Then I'll reinstall this PR and let you know what happens. I have no worries on bandwidth so I am happy to download the game again.

**Comment by LovingMelody** [comment]
Shouldn't require reinstalling the game. Just ensure your flake input is targeting the `update-star-citizen` branch

**Comment by damccull** [comment]
I agree with you, but I did do that and nothing changed. So I'm going the nuclear route just to ensure there's nothing weird going on in my system. I've already begun, but it won't be a long process.

**Comment by damccull** [comment]
Well, this fixed it. Not sure what it was holding it back. Shortcut is working fine now. I wonder if it was just my shortcut that was jacked up. Either way, thank you for the effort in fixing this.

**Comment by damccull** [comment]
Would you mind telling me what was causing the problem so I can learn a bit more about wine and nix?

**Comment by LovingMelody** [comment]
the launcher cant handle the logs outputting to the journal (which is what the desktop  shortcut does on gnome,  it uses systemd-run) this is just a work around for that by checking if the command is run from the terminal and if it isn't, route the output to a file. 
Proton gets around this through other means: https://github.com/ValveSoftware/wine/commit/4703b100e324673214247b60a1172fae5f10c22e

**Comment by damccull** [comment]
How weird. I didn't think it would care where the logs go. Thanks for the link.

**Comment by LovingMelody** [comment]
umu build failure is caused by https://github.com/Open-Wine-Components/umu-launcher/issues/296

**Comment by LovingMelody** [comment]
pinging @fufexan for review

**Review by fufexan — APPROVED** [review]

**Pull request merged**
